# Github Enforced
safe: true
lsi: false

#General
timezone: US/Central
encoding: utf-8
url: http://blog.voltaicideas.net

# Excludes
exclude: [
  'README.md',
  'Gemfile',
  'Gemfile.lock',
  'CNAME',
  'assets/css',
  'assets/js',
  'assets/node_modules',
  'assets/gulpfile.js',
  'assets/package.json',
]

# Code highlighting
highlighter: pygments

# links
permalink: date

# Markdown
markdown: redcarpet
redcarpet:
  smart: true
  extensions: [
    'no_intra_emphasis',
    'tables',
    'disable_indented_code_blocks',
    'strikethrough',
    'superscript',
    'underline',
    'highlight'
  ]

# Defaults for the front matter
defaults:
  -
    scope:
      path: "" # all files
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts" # all posts
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Extra Variables for the templates
owner:
  name: Andrew Senetar
  email: arsenetar@gmail.com
title: Blog@VoltaicIdeas
